#User.db.url=UrlDerDatenbank
#User.db.user=TestUser
#User.db.pw=TestPW

#Oliver 
db.url=jdbc:mariadb://localhost:3306/mydb?allowMultiQueries=true
db.user=root
db.pw=

#Jonas
Schueler.db.url=jdbc:mariadb://localhost:3306/mydb?allowMultiQueries=true
Schueler.db.user=root
Schueler.db.pw=

#Jonas2 zuhause
Jonas.db.url=jdbc:mariadb://localhost:3306/mydbjonas?allowMultiQueries=true
Jonas.db.user=root
Jonas.db.pw=

#Kilian
db.url=jdbc:mariadb://localhost:3306/mydb?allowMultiQueries=true
db.user=root
db.pw=

#David
db.url=jdbc:mariadb://localhost:3306/mydb?allowMultiQueries=true
db.user=root
NameDesUsers.db.pw=