#User.db.url=UrlDerDatenbank
#User.db.user=TestUser
#User.db.pw=TestPW

#Oliver 
oblass.db.url=jdbc:mariadb://localhost:3306/kuabdb?allowMultiQueries=true
oblass.db.user=test
oblass.db.pw=

#Jonas
jonas.paessler.db.url=jdbc:mariadb://localhost:3307/mydb?allowMultiQueries=true
jonas.paessler.db.user=root
jonas.paessler.db.pw=

#Kilian
KVogel.db.url=jdbc:mariadb://localhost:3306/mydb?allowMultiQueries=true
KVogel.db.user=root
KVogel.db.pw=

#David
Schueler.db.url=jdbc:mariadb://localhost:3307/Gruppe5_Projekt?allowMultiQueries=true
Schueler.db.user=root
Schueler.db.pw=