
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup mariadb
    - uses: getong/mariadb-action@v1.11
      with:
        host port: 3800 # Optional, default value is 3306. The port of host
        container port: 3307 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
        mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.DatabasePassword }}

    - uses: actions/checkout@v4
    - name: Set up JDK 21
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: edit url property
    - uses: Reedyuk/write-properties@v1.0.3
      with:
    # The path to properties file to write
        path: "src/main/resources/DbData.properties"
    # The property you want to write
        property: ${{github.actor}} + ".db.url"
    # The value write to the property
        value: "jdbc:mariadb://localhost:3306/some_test?allowMultiQueries=true"
        
    - name: edit user property
    - uses: Reedyuk/write-properties@v1.0.3
      with:
    # The path to properties file to write
        path: "src/main/resources/DbData.properties"
    # The property you want to write
        property: ${{github.actor}} + ".db.user"
    # The value write to the property
        value: ${{github.actor}}
        
    - name: edit pw property
    - uses: Reedyuk/write-properties@v1.0.3
      with:
    # The path to properties file to write
        path: "src/main/resources/DbData.properties"
    # The property you want to write
        property: ${{github.actor}} + ".db.pw"
    # The value write to the property
        value: ${{ secrets.DatabasePassword }}
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
    - uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
